# Generated by Django 4.2.4 on 2023-08-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
