# Generated by Django 4.2.4 on 2023-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
