# Generated by Django 4.2.4 on 2023-09-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_quantity_product_price_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_pc',
        ),
    ]
