# Generated by Django 4.2.4 on 2023-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('username', models.EmailField(max_length=254)),
                ('contact_email', models.EmailField(max_length=254)),
                ('pin', models.IntegerField(max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_established', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
