# Generated by Django 4.2.4 on 2023-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('franchise', 'Franchise')], default='franchise', max_length=20),
        ),
    ]
