# Generated by Django 4.2.4 on 2023-08-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_alter_franchise_pin'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='franchise.franchise'),
            preserve_default=False,
        ),
    ]
