# Generated by Django 4.2.4 on 2023-09-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sales_product_remove_sales_quantity_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity_type',
        ),
    ]
